name: Function.Iterator
author: ibolmo
category: Utilities
tags: [iterator, generator]

authors: "[Olmo Maldonado](http://ibolmo.com)"
web: "[ibolmo.com](http://ibolmo.com)"
description: "Function.Iterator. A class to help you create generators."
license: "[MIT License](http://mootools.net/license.txt)"
copyright: "&copy; [Olmo Maldonado](http://ibolmo.com/)"
